### ISSUE TITLE
关于对SD_CASSI系统的测试

### ISSUE THREAD

**Issue by wangyunzhen123** [ChenYong1993/LRSDN#3]
在测试SD_CASSI系统效果的过程中，我将将DD_CASSI中的dd_mask（大小为512 * 512 * 31）换成了SD_CASSI系统中的sd_mask（使用论文TS A- Net中的mask.mat，其大小为258 * 258 * 31），并将大小512 * 512 * 31的ballons31_cassi.mat裁剪成258 * 258 * 31以适配sd_mask，最终进行了测试，但效果远不如论文所述，作者能提供有关SD_CASSI系统的相关文件和代码吗？
<img width="360" alt="Snipaste_2024-06-11_00-06-31" src="https://github.com/ChenYong1993/LRSDN/assets/68804220/050e0d23-552e-4a53-90de-cdfaf881ba3f">

**Comment by hwd963737** [comment]
请问你找到SD-CCASI的仿真代码了吗？
